---
abstract: 'Install the Map::Tube concrete metro modules.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Map-Tube-Metro
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Map::Tube::Athens: 0.01
  Map::Tube::Barcelona: 0.76
  Map::Tube::Beijing: 0.012003
  Map::Tube::Berlin: 2021.0709
  Map::Tube::Bielefeld: 2020.033
  Map::Tube::Bucharest: 0.11
  Map::Tube::Budapest: 0.07
  Map::Tube::Copenhagen: 0.04
  Map::Tube::Delhi: 0.97
  Map::Tube::Dnipropetrovsk: 0.05
  Map::Tube::Frankfurt: 0.04
  Map::Tube::Glasgow: 0.072001
  Map::Tube::Hamburg: 0.001001
  Map::Tube::Kazan: 0.04
  Map::Tube::Kharkiv: 0.08
  Map::Tube::Kiev: 0.07
  Map::Tube::KoelnBonn: 0.092001
  Map::Tube::Kolkatta: 0.33
  Map::Tube::KualaLumpur: 0.07
  Map::Tube::London: 1.41
  Map::Tube::Lyon: 0.062001
  Map::Tube::Madrid: 0.39
  Map::Tube::Malaga: 0.18
  Map::Tube::Milan: 0.008
  Map::Tube::Minsk: 0.08
  Map::Tube::Moscow: 0.07
  Map::Tube::NYC: 0.33
  Map::Tube::Nanjing: 0.04
  Map::Tube::NizhnyNovgorod: 0.04
  Map::Tube::Novosibirsk: 0.05
  Map::Tube::Nuremberg: 0.06
  Map::Tube::Prague: 0.16
  Map::Tube::Rome: 1.01
  Map::Tube::SaintPetersburg: 0.08
  Map::Tube::Samara: 0.06
  Map::Tube::Singapore: 0.05
  Map::Tube::Sofia: 0.1
  Map::Tube::Tbilisi: 0.05
  Map::Tube::Tokyo: 0.6
  Map::Tube::Vienna: 0.09
  Map::Tube::Warsaw: 0.09
  Map::Tube::Yekaterinburg: 0.05
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Task-Map-Tube-Metro/issues
  homepage: https://github.com/michal-josef-spacek/Task-Map-Tube-Metro
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: git://github.com/michal-josef-spacek/Task-Map-Tube-Metro
version: '0.14'
